### PR TITLE
version 0.1.4, meta info updates and doc cleanup

### PR DESCRIPTION
**Pull request by svenkreiss**
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/s2sphere/3)

### CODE REVIEW

**Comment by danvk** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.rst, line 7 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-KGO4VU9It0DNpKINUJ7:-KGO4VUAS9XE18jx0WTj:1469327872) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/b5a2c6c19760fafad12f8085bf903c1ea44b3bba/README.rst#L7)):*
`on distributed indices` → `using distributed indices`

---

*[README.rst, line 9 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-KGO4isaqfDBLqxhyw5E:-KGO4isaqfDBLqxhyw5F:1365074512) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/b5a2c6c19760fafad12f8085bf903c1ea44b3bba/README.rst#L9)):*
Make these links?

---

*[docs/sphinx/index.rst, line 7 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-KGO54XEBFUtoPfbieEl:-KGO4uPGx-rzNwRIvufx:-754412972) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/b5a2c6c19760fafad12f8085bf903c1ea44b3bba/docs/sphinx/index.rst#L7)):*
Is this file generated from `README.rst`? If so, can we ensure that they stay in sync somehow? Or at least include the relevant commands to generate it in `README.rst`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3)*

**Comment by svenkreiss** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.rst, line 7 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-KGO4VU9It0DNpKINUJ7:-KGO7__aYRm3fx0aqgYo:-499146009) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/b5a2c6c19760fafad12f8085bf903c1ea44b3bba/README.rst#L7)):*
Done.

---

*[README.rst, line 9 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-KGO4isaqfDBLqxhyw5E:-KGO75nRMbihpd3E8JDZ:2094995258) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/b5a2c6c19760fafad12f8085bf903c1ea44b3bba/README.rst#L9)):*
they are links

---

*[docs/sphinx/index.rst, line 7 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-KGO54XEBFUtoPfbieEl:-KGO7FDEgxfqFOC2EPhS:-438603106) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/b5a2c6c19760fafad12f8085bf903c1ea44b3bba/docs/sphinx/index.rst#L7)):*
no, this is not generated. Maybe we should remove some stuff from the readme and just point to the documentation, but maybe we can do that later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3)*

**Comment by svenkreiss** [comment]
sorry for the additional commits. Branch can be merged and builds on Travis now.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-:-KGOVsbOUpXyyRLgIUc5:-1741677846)*

**Comment by danvk** [comment]
Is the merge commit necessary? (I usually rebase instead.)

---

Reviewed 4 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.rst, line 9 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-KGO4isaqfDBLqxhyw5E:-KGObpxBLsWIvGimLo8W:596087542) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/b5a2c6c19760fafad12f8085bf903c1ea44b3bba/README.rst#L9)):*
I meant the RST equivalent of:

```markdown
[Documentation](http://s2sphere.readthedocs.org)
```

or are you saying that this is the equivalent?

---

*[docs/sphinx/index.rst, line 7 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-KGO54XEBFUtoPfbieEl:-KGOcGBWo_mfmdQfSRkw:1532734731) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/b5a2c6c19760fafad12f8085bf903c1ea44b3bba/docs/sphinx/index.rst#L7)):*
If it's manual, I'd prefer to remove the duplication or automate it somehow. No two things ever stay in sync unless you force them to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-:-KGOcZVHPTiHFuRr39Uv:-1736888958)*

**Comment by svenkreiss** [comment]
true, that's nicer.

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.rst, line 9 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-KGO4isaqfDBLqxhyw5E:-KGOhtB4Xqud6TU_kccQ:-499146009) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/b5a2c6c19760fafad12f8085bf903c1ea44b3bba/README.rst#L9)):*
Done.

---

*[docs/sphinx/index.rst, line 7 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-KGO54XEBFUtoPfbieEl:-KGOhvkkQz0eZyE_geN8:-499146009) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/b5a2c6c19760fafad12f8085bf903c1ea44b3bba/docs/sphinx/index.rst#L7)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-:-KGOhyxbWq9LMi-1_coQ:-16234401)*

**Comment by danvk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/3#-:-KGOkC7mroRlq7Wd4qtR:1417088721)*

**Pull request merged**
