### PR TITLE
linting with flake8

### PR DESCRIPTION
**Pull request by svenkreiss**
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/s2sphere/8)

### CODE REVIEW

**Comment by danvk** [comment]
Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 56 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmwdJRT6J_ACmLfViP:-KGmwdJRT6J_ACmLfViQ:-7303062) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/.travis.yml#L56)):*
What is hacking and why do we need it? (I don't see it referenced anywhere.)

---

*[circle.yml, line 3 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmufIITh5kmpow-0Pi:-KGmufIITh5kmpow-0Pj:-1202880782) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/circle.yml#L3)):*
Create a `test.sh` script? These lines are getting a little long.

Alternatively, you can create a [YAML variable][1].

[1]: https://en.wikipedia.org/wiki/YAML#Repeated_nodes

---

*[setup.cfg, line 2 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmv4vPjYfbun_A1IbA:-KGmv4vPjYfbun_A1IbB:261133562) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/setup.cfg#L2)):*
Does this file support comments? If so, please document what this code is and why we want to ignore it.

---

*[s2sphere/__init__.py, line 2 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmvQ3kmGzLzlMk37jz:-KGmvQ3kmGzLzlMk37k-:1733415424) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/s2sphere/__init__.py#L2)):*
What is `noqa`? How about a comment.

---

*[s2sphere/sphere.py, line 14 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmvc6X8uDKtaXEz6nN:-KGmvc6X8uDKtaXEz6nO:-1562240697) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/s2sphere/sphere.py#L14)):*
Is this coming directly from `s2angle.h`?

---

*[tests/sphere_test.py, line 1508 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmw8IYVHR5USzugcn7:-KGmw8IYVHR5USzugcn8:1594991985) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/tests/sphere_test.py#L1508)):*
these don't fit on one line?

---

*[tests/sphere_test.py, line 1812 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmwNLuCN-27n6pXwal:-KGmwNLuCN-27n6pXwam:1599495814) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/tests/sphere_test.py#L1812)):*
If this var is unused, it would be better to replace it with:

```python
cell0tr.get_rect_bound()
```

so that the code still gets execute (it could still break the test if it threw an exception, for example).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8)*

**Comment by danvk** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8)*

**Comment by svenkreiss** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 56 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmwdJRT6J_ACmLfViP:-KGn8a1xhmdZl_q-W7rV:939534219) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/.travis.yml#L56)):*
It is a plugin to flake8. Adds more checks that I find pretty useful.

---

*[circle.yml, line 3 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmufIITh5kmpow-0Pi:-KGn8mDCwZBc8Ct_Zzec:-968411512) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/circle.yml#L3)):*
We are not at all using CircleCI as we are supposed to. Testing multiple versions in Python is much better supported in TravisCI. Was thinking of switching the purpose of Travis and Circle: test the C and Python compatibility on CircleCI and test multiple Python versions on TravisCI. But the original test of the C library was written for Travis :(

---

*[setup.cfg, line 2 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmv4vPjYfbun_A1IbA:-KGn9dncHQtP7s-hqYJU:-499146009) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/setup.cfg#L2)):*
Done.

---

*[s2sphere/__init__.py, line 2 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmvQ3kmGzLzlMk37jz:-KGn9fqKE8wgZFbQmz0f:1231410854) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/s2sphere/__init__.py#L2)):*
It's a flake8 thing. A comment that signals flake8 to ignore the file. I would also prefer if flake8 handled `__init__.py` files better, but this was the best I could find.

---

*[s2sphere/sphere.py, line 14 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmvc6X8uDKtaXEz6nN:-KGnAI11DmzEvxkO8vnD:-363079020) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/s2sphere/sphere.py#L14)):*
It is from `s1angle.h`: https://github.com/micolous/s2-geometry-library/blob/master/geometry/s2/s1angle.h

Why?

---

*[tests/sphere_test.py, line 1508 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmw8IYVHR5USzugcn7:-KGnB8kIK_-iQvSzfyji:-1864844148) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/tests/sphere_test.py#L1508)):*
79 chars is pretty short

---

*[tests/sphere_test.py, line 1812 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmwNLuCN-27n6pXwal:-KGnBQDsndPSM7vbAL1_:-499146009) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/tests/sphere_test.py#L1812)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8)*

**Comment by svenkreiss** [comment]
Review status: 7 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[tests/sphere_test.py, line 1508 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmw8IYVHR5USzugcn7:-KGnCQmRSFnOlKt-Lk0M:-154631598) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/tests/sphere_test.py#L1508)):*
it actually does, but the lines above dont and this keeps it symmetric

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8)*

**Comment by danvk** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[circle.yml, line 3 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmufIITh5kmpow-0Pi:-KGnCVAcRvZUZPs_KTZ2:-1849821834) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/circle.yml#L3)):*
I think it would make sense to use either CircleCI or Travis, rather than both. With both, our tests will flake if either of them are having issues.

My suggestion is a little more concrete though—just to reduce code duplication by factoring out the `python -V && pip install .[tests] && flake8 && nosetests -vv --exclude=compare_implementations_test"` that's repeated 3x.

---

*[s2sphere/__init__.py, line 2 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmvQ3kmGzLzlMk37jz:-KGnD1MKQUKS06AjmAP1:1020710665) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/s2sphere/__init__.py#L2)):*
Does the line have to be exactly this? Could it be

```python
# flake8: noqa  (don't lint this file)
```

or

```python
# flake8: noqa
# (don't lint this file)
```

---

*[s2sphere/sphere.py, line 14 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmvc6X8uDKtaXEz6nN:-KGnDFmkecV4vVpva-MW:1238418878) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/s2sphere/sphere.py#L14)):*
Just wondering about the rewording and whether it made our docstring more or less closely match the one in `s1angle.h`. I guess we will need to do some sort of manual QA on these, since comments about copy constructors don't make as much sense in Python.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-:-KGnDgtvQV05zWltsR0P:1417088721)*

**Comment by svenkreiss** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[circle.yml, line 3 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmufIITh5kmpow-0Pi:-KGnJYAlCabjVdVN0GiX:-1468431183) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/circle.yml#L3)):*
never used a YAML variable. This seems to be a good solution. Testing it now.

---

*[s2sphere/__init__.py, line 2 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmvQ3kmGzLzlMk37jz:-KGnJhPa4KnG2LNO6uQq:-499146009) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/s2sphere/__init__.py#L2)):*
Done.

---

*[s2sphere/sphere.py, line 14 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8#-KGmvc6X8uDKtaXEz6nN:-KGnK2433LsONPnt89C5:-171271806) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/42f7edd0610b297912cf5178cd02a20d9bc03e1e/s2sphere/sphere.py#L14)):*
our doc is not in great shape right now. The comments that are in are more or less in by accident. Was planning to do a proper pass and extract the C++ comments together with a refactor into `R1`, `S1` and `S2` sub-packages. Maybe that should be done before we talk about it publicly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8)*

**Comment by danvk** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/8)*

**Pull request merged**
