### PR TITLE
implement CellId.walk() and CellId.walk_fast()

### PR DESCRIPTION
**Pull request by svenkreiss**
more pythonic iterator over cells at a given level

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/s2sphere/10)

### CODE REVIEW

**Comment by danvk** [comment]
A few comments. At a higher level, do we want to preserve the 1↔1 mapping between C++ and Python classes? If so, `walk` and `walk_fast` should be provided in a separate module.

<details><summary><i>Previously, svenkreiss (Sven Kreiss) wrote…</i></summary>
> #### implement CellId\.walk\(\) and CellId\.walk\_fast\(\)
> 
> more pythonic iterator over cells at a given level
> 
> 
> </details>


---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[s2sphere/sphere.py, line 1139 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb3DSwyVKMsYdi6LKk:-KHb3DSwyVKMsYdi6LKl:789201649) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1139)):*
> ```Python
>             Iterator over instances of :class:`CellId`s.
>         """
>         cellid = cls.begin(level).id()
> ```

Python question: why do `cls.begin` rather than `CellId.begin`?

---

*[s2sphere/sphere.py, line 1139 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb4UyDQ7ihV_2z5Z2g:-KHb4UyDQ7ihV_2z5Z2h:-1384720425) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1139)):*
> ```Python
>             Iterator over instances of :class:`CellId`s.
>         """
>         cellid = cls.begin(level).id()
> ```

The naming here is a bit confusing -- is `cellid` a `CellId` or an `int`?

---

*[s2sphere/sphere.py, line 1141 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb3TG27bcN-RXdZmZi:-KHb3TG27bcN-RXdZmZj:1157347794) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1141)):*
> ```Python
>         cellid = cls.begin(level).id()
>         endid = cls.end(level).id()
>         increment = cls.begin(level).lsb() << 1
> ```

This is cryptic; add a comment (also in `walk_fast`)

---

*[s2sphere/sphere.py, line 1154 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb3gSvltitVzUu9kFf:-KHb3gSvltitVzUu9kFg:-1144413503) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1154)):*
> ```Python
> 
>         Use with caution: This modifies the underlying ``id`` of a single
>         :class:`CellId` instance for performance reasons.
> ```

I'd rewrite this comment to be more oriented towards a user of this function (and less about implementation details). For instance, something like

```
Use with caution: this repeatedly yields mutates a single object with a changing ``id``.
If you save the object, it will change out from underneath you.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-:-KHb4cYq5g9hdt2vgG2P:552255544)*

**Comment by svenkreiss** [comment]
Thanks for the comments.

That 1 to 1 mapping never existed. This was one of the comments from the original author that he regretted not having preserved that better.

<details><summary><i>Previously, danvk (Dan Vanderkam) wrote…</i></summary>
> A few comments. At a higher level, do we want to preserve the 1↔1 mapping between C++ and Python classes? If so, `walk` and `walk_fast` should be provided in a separate module.</details>


---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[s2sphere/sphere.py, line 1139 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb3DSwyVKMsYdi6LKk:-KHb5VqTUEY3Oe7VwME2:770757031) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1139)):*
<details><summary><i>Previously, danvk (Dan Vanderkam) wrote…</i></summary>
> Python question: why do `cls.begin` rather than `CellId.begin`?</details>
This has something to do with the behavior for derived classes. I had never used it like this before (I usually use `@staticmethod` and not `@classmethod`), but I think it could make sense so that `begin` is called of the derived class in case it is overwritten.

---

*[s2sphere/sphere.py, line 1139 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb4UyDQ7ihV_2z5Z2g:-KHb672IujeDFeYZmiVF:56305262) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1139)):*
<details><summary><i>Previously, danvk (Dan Vanderkam) wrote…</i></summary>
> The naming here is a bit confusing -- is `cellid` a `CellId` or an `int`?</details>
an `int`.  I am struggling to come up with a better name. 

---

*[s2sphere/sphere.py, line 1141 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb3TG27bcN-RXdZmZi:-KHePqr4pNczIDq3oRBY:-499146009) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1141)):*
<details><summary><i>Previously, danvk (Dan Vanderkam) wrote…</i></summary>
> This is cryptic; add a comment (also in `walk_fast`)</details>
Done.

---

*[s2sphere/sphere.py, line 1154 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb3gSvltitVzUu9kFf:-KHePreEmqQty1h2aAnz:-499146009) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1154)):*
<details><summary><i>Previously, danvk (Dan Vanderkam) wrote…</i></summary>
> I'd rewrite this comment to be more oriented towards a user of this function (and less about implementation details). For instance, something like
> 
> ```
> Use with caution: this repeatedly yields mutates a single object with a changing ``id``.
> If you save the object, it will change out from underneath you.
> ```</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-:-KHb5Erj1uYBNu1N7c4p:-433469473)*

**Comment by danvk** [comment]
Some more suggestions for the comments, otherwise :lgtm: 

<details><summary><i>Previously, svenkreiss (Sven Kreiss) wrote…</i></summary>
> Thanks for the comments.
> 
> That 1 to 1 mapping never existed. This was one of the comments from the original author that he regretted not having preserved that better.</details>


---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[s2sphere/sphere.py, line 1139 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb4UyDQ7ihV_2z5Z2g:-KHeSCopyrSUfI63O_-C:-1943245300) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1139)):*
<details><summary><i>Previously, svenkreiss (Sven Kreiss) wrote…</i></summary>
> an `int`.  I am struggling to come up with a better name. </details>
`cell_id_int`?

---

*[s2sphere/sphere.py, line 1141 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb3TG27bcN-RXdZmZi:-KHeSLUuKZZ1jDZuCdEJ:121739575) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1141)):*
<details><summary><i>Previously, svenkreiss (Sven Kreiss) wrote…</i></summary>
> Done.</details>
This still wasn't clear to me... @svenkreiss and I hashed it out. How about something like this?

```
The 64-bit ID has:
- 3 bits to encode the face
- 0-60 bits to encode the position
- a 1

The final 1 is the least significant bit. Doubling it yields the increment between positions as 64-bit IDs.
```

---

*[s2sphere/sphere.py, line 1154 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb3gSvltitVzUu9kFf:-KHeUu_2gUsK2X4zL7AJ:515878968) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1154)):*
<details><summary><i>Previously, svenkreiss (Sven Kreiss) wrote…</i></summary>
> Done.</details>
You've got "use with caution" twice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-:-KHeUzetAehxu56t6qOP:1140940389)*

**Comment by svenkreiss** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[s2sphere/sphere.py, line 1154 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-KHb3gSvltitVzUu9kFf:-KHelJFKJ47PiCxC4XHO:-499146009) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/532c11911349de2a7a2289164209b32fe6e53d5e/s2sphere/sphere.py#L1154)):*
<details><summary><i>Previously, danvk (Dan Vanderkam) wrote…</i></summary>
> You've got "use with caution" twice.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10)*

**Comment by danvk** [comment]
:shipit: 

<details><summary><i>Previously, danvk (Dan Vanderkam) wrote…</i></summary>
> Some more suggestions for the comments, otherwise :lgtm: </details>


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/10#-:-KHemcg3G9IjxTZzteda:1148172450)*

**Pull request merged**
