### PR TITLE
tests on circleci

### PR DESCRIPTION
**Pull request by svenkreiss**
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/s2sphere/6)

### CODE REVIEW

**Comment by danvk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[circle.yml, line 11 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/6#-KGSU8n63AKc-JkvBel2:-KGSU8n63AKc-JkvBel3:1200072635) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/13aac3673e016426a780b1fa7854272de7dd62be/circle.yml#L11)):*
As a sanity check, add a `print` statement to the tests which logs the current Python version.

---

*[circle.yml, line 12 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/6#-KGSU3fex3EDz1xv5WNk:-KGSU3fex3EDz1xv5WNl:-610313222) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/13aac3673e016426a780b1fa7854272de7dd62be/circle.yml#L12)):*
Do we care about Python 3.4? 3.5 has been out for ~8 months now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/6)*

**Comment by svenkreiss** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[circle.yml, line 11 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/6#-KGSU8n63AKc-JkvBel2:-KGSV1bsQYrhM5cFC8yi:-499146009) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/13aac3673e016426a780b1fa7854272de7dd62be/circle.yml#L11)):*
Done.

---

*[circle.yml, line 12 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/6#-KGSU3fex3EDz1xv5WNk:-KGSV3U-AbFDyDwQGH4N:-289647902) ([raw file](https://github.com/sidewalklabs/s2sphere/blob/13aac3673e016426a780b1fa7854272de7dd62be/circle.yml#L12)):*
Supporting it comes for free currently. We can make a decision to drop it when we have a use case that is not supported in 3.4. There are some really old linux boxes around that might better support Python 3.4. It is in the `classifiers` in the `setup.py`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/6)*

**Comment by danvk** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/6#-:-KGSmeUo-3YlpRoHnXpy:1417088721)*

**Comment by danvk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/s2sphere/6)*

**Pull request merged**
